name: Build Workflow   # Just a name for humans

on:
  workflow_call:       # 👈 This makes it reusable!
    inputs:            # (Optional) Define inputs like function args
      node-version:
        type: string
        required: true
    secrets:           # (Optional) Define secrets needed
      NPM_TOKEN:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
